# Generated by Django 5.2.12 on 2026-03-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('paid', '已付款'), ('shipping', '出貨中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='訂單狀態')),
                ('total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='總金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member', verbose_name='會員')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='單價')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
            ],
        ),
    ]
