# Generated by Django 5.2.12 on 2026-03-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('paid', '已付款'), ('shipping', '出貨中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='狀態'),
        ),
    ]
