# Generated by Django 5.2.12 on 2026-03-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='價格')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存')),
                ('status', models.CharField(choices=[('on', '上架'), ('off', '下架')], default='on', max_length=3, verbose_name='狀態')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='商品圖片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='分類')),
            ],
        ),
    ]
