# Generated by Django 5.2.12 on 2026-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
            ],
        ),
    ]
